namespace: epfl_si
name: k8s

version: 0.4.0

readme: README.md

authors:
- EPFL SI ISAS-FSD <isas-fsd@groupes.epfl.ch>

description: Like `kubernetes.core.k8s`, but with saner authentication

license:
- GPL-2.0-or-later

tags:
- k8s

dependencies:
  kubernetes.core: ">=5.0.0"

repository: https://github.com/epfl-si/ansible-collection-k8s

documentation: https://github.com/epfl-si/ansible-collection-k8s

homepage: https://github.com/epfl-si/ansible-collection-k8s

# The URL to the collection issue tracker
issues: https://github.com/epfl-si/ansible-collection-k8s/issues

build_ignore: []
